const fs = require('fs');
const path = require('path');

const DB_PATH = path.join(__dirname, 'db.json');

// ===== HOW TO ADD YOUR OWN IMAGES =====
// 1. Drop your image file into the "photos/" folder (e.g., my-bag.jpg)
// 2. Add a new entry below like:
//       'my-bag': '/photos/my-bag.jpg',
// 3. Use it in a product below:
//       imageUrls: [ photoMap['my-bag'], ... ]
// 4. Run: cd backend && node seed.js && node server.js
// ========================================
const photoMap = {
  'coach-pink': '/photos/bag-pink.jfif',
  'coach-heart': '/photos/bag-heart.jfif',
  'coach-tan': '/photos/bag-tan.jfif',
  'coach-giftbox': '/photos/coachgiftbox.jfif',
  'adidas-white': '/photos/adidaswhite.jpeg',
  'burgundy': '/photos/burgundy.jpeg',
  'burgundy-adidas': '/photos/burgundyadidas.jpeg',
  'denim': '/photos/denim.jpeg',
  'grey': '/photos/grey.jpeg',
  'heart-adidas': '/photos/heartadidas.jpeg',
  'hermes': '/photos/hermes.jpeg',
  'leopard': '/photos/leopard.jpeg',
  'letter': '/photos/letter.jfif',
  'male-nike': '/photos/malenike.jpeg',
  'multicolor': '/photos/multicolor.jpeg',
  'red-set': '/photos/redset.jfif',
  'suede': '/photos/suede.jpeg',
  'download-1': '/photos/download (1).jfif',
  'download-2': '/photos/download (2).jfif',
  'download-3': '/photos/download (3).jfif',
  'download': '/photos/download.jfif',
};

const products = [
  {
    id: 'p1',
    title: 'Lavender Dream Tote',
    description: 'Spacious tote bag crafted from premium vegan leather with gold-tone hardware. Perfect for everyday elegance.',
    price: 45000,
    originalPrice: 55000,
    category: 'Totes',
    imageUrls: [
      photoMap['coach-pink'],
      photoMap['coach-giftbox'],
      photoMap['letter'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    title: 'Rose Gold Mini Crossbody',
    description: 'Compact crossbody bag with adjustable chain strap and sparkling crystal embellishments.',
    price: 32000,
    originalPrice: 38000,
    category: 'Mini Bags',
    imageUrls: [
      photoMap['coach-heart'],
      photoMap['coach-giftbox'],
      photoMap['heart-adidas'],
    ],
    inStock: true,
    tags: ['HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    title: 'Blush Pearl Clutch',
    description: 'Elegant clutch adorned with freshwater pearl detailing. Removable wrist strap included.',
    price: 28000,
    originalPrice: null,
    category: 'Accessories',
    imageUrls: [
      photoMap['coach-tan'],
      photoMap['suede'],
      photoMap['download-2'],
    ],
    inStock: true,
    tags: ['BESTSELLER', 'HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    title: 'Dusty Pink Saddle Bag',
    description: 'Modern saddle bag silhouette with magnetic closure and detachable shoulder strap.',
    price: 52000,
    originalPrice: 65000,
    category: 'Mini Bags',
    imageUrls: [
      photoMap['coach-pink'],
      photoMap['suede'],
      photoMap['letter'],
    ],
    inStock: true,
    tags: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    title: 'Mauve Silk Scarf Set',
    description: 'Set of two luxury silk scarves with hand-rolled edges. Can be worn as accessories or bag ties.',
    price: 15000,
    originalPrice: 20000,
    category: 'Accessories',
    imageUrls: [
      photoMap['download-3'],
      photoMap['download-2'],
      photoMap['letter'],
    ],
    inStock: true,
    tags: ['ON SALE'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    title: 'Petal Pink Shopper',
    description: 'Oversized shopper bag ideal for work or travel. Features interior zip pocket and reinforced handles.',
    price: 62000,
    originalPrice: null,
    category: 'Totes',
    imageUrls: [
      photoMap['coach-heart'],
      photoMap['coach-giftbox'],
      photoMap['download'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p7',
    title: 'Crystal Hairpin Set',
    description: 'Set of 3 crystal-embellished hairpins in rose gold. Adds instant glamour to any look.',
    price: 8500,
    originalPrice: 12000,
    category: 'Accessories',
    imageUrls: [
      photoMap['download-1'],
      photoMap['download-2'],
      photoMap['download-3'],
    ],
    inStock: true,
    tags: ['HOT', 'ON SALE'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p8',
    title: 'Blush Beaded Evening Bag',
    description: 'Intricately beaded evening bag with satin lining and magnetic snap closure.',
    price: 38000,
    originalPrice: 45000,
    category: 'Mini Bags',
    imageUrls: [
      photoMap['coach-tan'],
      photoMap['suede'],
      photoMap['leopard'],
    ],
    inStock: true,
    tags: ['HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p9',
    title: 'Large Weekend Duffle',
    description: 'Spacious weekend duffle in soft pink vegan leather. Features shoe compartment and luggage sleeve.',
    price: 75000,
    originalPrice: 90000,
    category: 'Totes',
    imageUrls: [
      photoMap['denim'],
      photoMap['grey'],
      photoMap['multicolor'],
    ],
    inStock: true,
    tags: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p10',
    title: 'Gold Hoop Earrings',
    description: 'Oversized gold-tone hoop earrings with subtle crystal drop detail. Hypoallergenic posts.',
    price: 12000,
    originalPrice: null,
    category: 'Accessories',
    imageUrls: [
      photoMap['download'],
      photoMap['download-1'],
      photoMap['download-2'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p11',
    title: 'Mini Basket Weave Bag',
    description: 'Summer-ready mini basket bag with leather trim and cute fruit-shaped charm.',
    price: 25000,
    originalPrice: 32000,
    category: 'Mini Bags',
    imageUrls: [
      photoMap['coach-pink'],
      photoMap['letter'],
      photoMap['download-3'],
    ],
    inStock: true,
    tags: ['ON SALE'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p12',
    title: 'ByAsa Signature Tote',
    description: 'The iconic ByAsa tote in signature blush pink. Features branded dust bag and authenticity card.',
    price: 85000,
    originalPrice: null,
    category: 'Totes',
    imageUrls: [
      photoMap['coach-heart'],
      photoMap['coach-giftbox'],
      photoMap['red-set'],
    ],
    inStock: true,
    tags: ['BESTSELLER', 'HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p13',
    title: 'Classic White Sneakers',
    description: 'Premium white sneakers with clean silhouette. Versatile staple for any wardrobe.',
    price: 38000,
    originalPrice: 45000,
    category: 'Sneakers',
    imageUrls: [
      photoMap['adidas-white'],
      photoMap['download-1'],
      photoMap['download-2'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p14',
    title: 'Burgundy Adidas Trainers',
    description: 'Rich burgundy adidas trainers with comfort cushioning and stylish design.',
    price: 42000,
    originalPrice: 50000,
    category: 'Sneakers',
    imageUrls: [
      photoMap['burgundy-adidas'],
      photoMap['burgundy'],
      photoMap['download-3'],
    ],
    inStock: true,
    tags: ['HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p15',
    title: 'Heart Print Adidas',
    description: 'Adidas sneakers featuring a playful heart print design. Bold and trendy.',
    price: 40000,
    originalPrice: null,
    category: 'Sneakers',
    imageUrls: [
      photoMap['heart-adidas'],
      photoMap['burgundy'],
      photoMap['download'],
    ],
    inStock: true,
    tags: ['HOT', 'BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p16',
    title: 'Nike Men Running Shoes',
    description: 'High-performance Nike running shoes for men. Breathable and lightweight.',
    price: 52000,
    originalPrice: 60000,
    category: 'Sneakers',
    imageUrls: [
      photoMap['male-nike'],
      photoMap['download-1'],
      photoMap['download-2'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p17',
    title: 'Hermes Style Leather Bag',
    description: 'Elegant leather handbag inspired by luxury French design. Timeless investment piece.',
    price: 120000,
    originalPrice: 150000,
    category: 'Handbags',
    imageUrls: [
      photoMap['hermes'],
      photoMap['coach-giftbox'],
      photoMap['red-set'],
    ],
    inStock: true,
    tags: ['BESTSELLER', 'HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p18',
    title: 'Leopard Print Statement Bag',
    description: 'Bold leopard print handbag with gold hardware. Make a statement wherever you go.',
    price: 58000,
    originalPrice: 70000,
    category: 'Handbags',
    imageUrls: [
      photoMap['leopard'],
      photoMap['suede'],
      photoMap['letter'],
    ],
    inStock: true,
    tags: ['HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p19',
    title: 'Red Luxury Gift Set',
    description: 'Complete luxury gift set in rich red. Perfect for gifting or treating yourself.',
    price: 65000,
    originalPrice: 80000,
    category: 'Handbags',
    imageUrls: [
      photoMap['red-set'],
      photoMap['coach-giftbox'],
      photoMap['denim'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p20',
    title: 'Suede Shoulder Bag',
    description: 'Buttery soft suede shoulder bag with elegant drape. Luxurious everyday companion.',
    price: 48000,
    originalPrice: 55000,
    category: 'Handbags',
    imageUrls: [
      photoMap['suede'],
      photoMap['coach-tan'],
      photoMap['leopard'],
    ],
    inStock: true,
    tags: ['ON SALE'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p21',
    title: 'Denim Statement Tote',
    description: 'Trendy denim tote bag with sturdy straps and spacious interior. Street-style ready.',
    price: 35000,
    originalPrice: 42000,
    category: 'Totes',
    imageUrls: [
      photoMap['denim'],
      photoMap['multicolor'],
      photoMap['grey'],
    ],
    inStock: true,
    tags: ['HOT'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p22',
    title: 'Grey Minimalist Handbag',
    description: 'Clean minimalist grey handbag with structured silhouette. Modern professional look.',
    price: 42000,
    originalPrice: null,
    category: 'Handbags',
    imageUrls: [
      photoMap['grey'],
      photoMap['denim'],
      photoMap['multicolor'],
    ],
    inStock: true,
    tags: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p23',
    title: 'Multicolor Canvas Bag',
    description: 'Vibrant multicolor canvas bag with playful stripes. Fun and functional.',
    price: 30000,
    originalPrice: 38000,
    category: 'Totes',
    imageUrls: [
      photoMap['multicolor'],
      photoMap['download-1'],
      photoMap['download-2'],
    ],
    inStock: true,
    tags: ['ON SALE'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p24',
    title: 'Burgundy Leather Handbag',
    description: 'Rich burgundy leather handbag with elegant hardware and structured design.',
    price: 55000,
    originalPrice: 65000,
    category: 'Handbags',
    imageUrls: [
      photoMap['burgundy'],
      photoMap['red-set'],
      photoMap['grey'],
    ],
    inStock: true,
    tags: ['BESTSELLER'],
    createdAt: new Date().toISOString(),
  },
];

const dbData = {
  products,
  orders: [],
};

fs.writeFileSync(DB_PATH, JSON.stringify(dbData, null, 2));
console.log(`✅ Seeded ${products.length} products to db.json`);
